<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<!--
   분류번호: #7 - 입주자 관리 페이지 : 전체 입주자 조회
   시작 날짜: 2024-07-08
   담당자: 박수지
-->


<!DOCTYPE html>
<html lang="en">
	<!-- ======= header <Head> 부분 ======= -->
	<jsp:include page="/WEB-INF/view/groupware/inc/headerHead.jsp"></jsp:include>
	
	<!-- ======= css ======= -->
	<link rel="stylesheet" href="/topaz/css/suji.css"> 
	
<body>
	<!-- ======= header <Body> 부분 ======= -->
	<jsp:include page="/WEB-INF/view/groupware/inc/hearderBody.jsp"></jsp:include>
	
	<!-- ======= sideBar 부분 ======= -->
	<jsp:include page="/WEB-INF/view/groupware/inc/sideBar.jsp"></jsp:include>

	<!-- =============================== Main 메인 시작 부분 ================================ -->
	<main id="main" class="main">
	
	<!-- Title 시작 -->
	<div class="pagetitle">
      <h1>입주자 관리</h1>
	</div><!-- Title 종료 -->

	<!-- section 시작 -->
    <section class="section">
    	<div class="pagetitle">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="/topaz/groupware/empMain">HOME</a></li>
          <li class="breadcrumb-item active">Resident List</li>
        </ol>
      </nav>
	</div><!-- End Page Title -->
	
 	<section class="section">
 	<div class="col-lg-12">
		<div class="card">
			<div class="card-body">
		    	<h5 class="card-title"></h5>
		    	<div class="container">
				    <div class="row mb-3">
				        <div class="col-md-1">
				            <label for="dong" class="form-label">동</label>
				        </div>
				        <div class="col-md-2">
				            <select id="dong" class="form-select" aria-label="Select dong">
								<option value = "">동을 선택하세요 </option>
				            </select>
				        </div>
				        <div class="col-md-1">
				            <label for="type" class="form-label">타입</label>
				        </div>
				        <div class="col-md-2">
				            <select id="type" class="form-select" aria-label="Select ho number">
								<option value ="">타입을 선택하세요</option>
				            </select>
				        </div>
				        <div class="col-md-1">
				            <label for="ho" class="form-label">호수</label>
				        </div>
				        <div class="col-md-2">
				            <select id="ho" class="form-select" aria-label="Select second ho number">
				                <option value ="">호수를 선택하세요</option>
				            </select>
				        </div>
				    </div>
				</div>

	<div class="search-container">
	  <div class="search-bar">
	    <form id="searchForm" class="search-form d-flex align-items-center">
	      <input type="text" id="searchWord" name="searchWord" placeholder="Search..." title="Enter search keyword">
	      <button type="submit" title="Search"><i class="bi bi-search"></i></button>
	      
	      <!-- 등록 버튼 -->
	      <a href="/topaz/groupware/resident/residentAdd" class="ml-2 btn btn-primary" title="Add New">입주자 등록</a>
	    </form>
	  </div>
	</div>

	<br>
    <!-- Table with stripped rows -->
    <table class="table table-hover">
      	<thead>
	         <tr>
			     <th scope="col">이름</th>
			     <th scope="col">동</th>
			     <th scope="col">호수</th>
	         </tr>
    	</thead>
      	<tbody id = "resident-list-tbody">
	
		</tbody>
	</table>
	<!-- End Table with stripped rows -->
	<nav aria-label="Page navigation example">
	  <ul class="pagination justify-content-center" id="pagination" >
	    <!-- Pagination links will be generated by JavaScript -->
	  </ul>
	</nav>
			</div>
		</div>
	</div>
	</section>
   	</section><!-- section 종료 -->

	</main><!-- End #main -->
	<!-- =============================== Main 메인 끝 부분 ================================ -->
	
	<!-- ======= footer 부분 ======= -->
	<jsp:include page="/WEB-INF/view/groupware/inc/footer.jsp"></jsp:include>
	<!-- 동, 타입, 호수 분류 -->
	<!-- Additional scripts -->
	<script type="text/javascript">
		$(document).ready(function() {
			// 동 데이터 요청
			$.ajax({
				url: '/topaz/groupware/resident/residentList/dong',
				method: 'POST',
				success: function(dongData) {
					console.log(dongData);
					dongData.forEach(function(item){
						console.log(item);
						$('#dong').append('<option value ="'+item+'">'+item+'</option>');
					});
				}
			});

			// 동 선택 시 타입 데이터 요청
			$('#dong').change(function(){
				if($('#dong').val() == ''){
					return;
				}

				$('#type').empty();
				$('#type').append('<option value="">타입을 선택하세요</option>');

				$.ajax({
					url: '/topaz/groupware/resident/residentList/type',
					method: 'POST',
					data: {'dong': $('#dong').val()},
					success: function(typeData) {
						console.log(typeData);
						typeData.forEach(function(item){
							$('#type').append('<option value="'+item+'">'+item+'</option>');
						});
					}
				});
			});

			$('#type').change(function(){
				if($('#type').val() == ''){
					return;
				}

				$('#ho').empty();
				$('#ho').append('<option value="">호수를 선택하세요</option>');

				$.ajax({
					url: '/topaz/groupware/resident/residentList/ho',
					method: 'POST',
					data: {'type': $('#type').val()},
					success: function(hoData) {
						console.log(hoData);
						hoData.forEach(function(item){
							console.log(item);
							$('#ho').append('<option value="'+item+'">'+item+'</option>');
						});
					}
				});
			});

			// 필터링 및 페이징 데이터 요청
			function loadPage(page, searchWord = '') {
				var dong = $('#dong').val();
				var type = $('#type').val();
				var ho = $('#ho').val();
				$.ajax({
					url: '/topaz/groupware/resident/residentList/filter',
					method: 'POST',
					data: {
						dong: dong,
						type: type,
						ho: ho,
						searchWord: searchWord,
						currentPage: page,
						rowPerPage: 5
					},
					success: function(response) {
						var tbody = $('table.table-hover tbody');
						tbody.empty();
						response.residents.forEach(function(item) {
							var row = '<tr data-href="/topaz/groupware/resident/residentDetail?gstId=' + item.gstId + '">';
							row += '<td>' + item.gstName + '</td>';
							row += '<td>' + item.dong + '</td>';
							row += '<td>' + item.ho + '</td>';
							row += '</tr>';
							tbody.append(row);
						});
						$('table.table-hover tbody tr').on('click', function() {
							window.location = $(this).data('href');
						});
						updatePagination(response.totalPages, page);
					}
				});
			}

			function updatePagination(totalPages, currentPage) {
		        var pagination = $('.pagination');
		        pagination.empty();
		        
		        // 처음 버튼
		        pagination.append('<li class="page-item ' + (currentPage === 1 ? 'disabled' : '') + '"><a class="page-link" data-page="' + 1 + '" href="#">&laquo;</a></li>');

		        var startPage = Math.max(currentPage - 2, 1);
		        var endPage = Math.min(currentPage + 2, totalPages);
		        
		        for (var i = startPage; i <= endPage; i++) {
		            var activeClass = (i === currentPage) ? 'active' : '';
		            var pageItem = '<li class="page-item ' + activeClass + '">';
		            pageItem += '<a class="page-link" data-page="' + i + '" href="#">' + i + '</a>';
		            pageItem += '</li>';
		            pagination.append(pageItem);
		        }
		        $('.pagination .page-link').on('click', function(e) {
					e.preventDefault();
					var page = $(this).data('page');
					var searchWord = $('#searchWord').val();
					loadPage(page);
				});

		       
		    }

			// 초기 데이터 로드
			loadPage(1);

			// 필터 변경 시 데이터 로드
			$('#dong, #type, #ho').change(function(){
				var searchWord = $('#searchWord').val();
				loadPage(1);
			});
			
			// 폼의 submit 이벤트 처리
		    $('#searchForm').submit(function(event) {
		      event.preventDefault();
		      var searchWord = $('#searchWord').val();
		      loadPage(1, searchWord);
		    });
		});
	</script>
	
</body>

</html>